project_id: "572367"
api_token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiJ3UUVxdmhVM3ZMT2EyWGljbVV5VCIsImp0aSI6ImJjN2QzOGYxZGY4MTg2NGE1ZWYyNjFhN2RlN2MwNzJkNmU1ZDEzZDBmMDRhZDQ5ODBmZDY0ZWIyZGQ2YWY1ZWU5ZWI4NzhkNDJlY2IyNWM3IiwiaWF0IjoxNjc4MDk1NDYyLjkwODg3NiwibmJmIjoxNjc4MDk1NDYyLjkwODg4NCwiZXhwIjoxNjgwNjgzODYyLjgwMDA2NSwic3ViIjoiMTMyNjY4NTUiLCJzY29wZXMiOlsicHJvamVjdCJdLCJkb21haW4iOm51bGwsImFzc29jaWF0aW9ucyI6WyIqIl0sInNlc3Npb24iOjB9.LUt9qwqGbYURAn4mkpRRIPKujv0-2Q93LRPm_fmlh8H6nARFqGegKKcXyOYxccSpeYWulA4BdCMFvgebmIWtU3hG7VJMymrizIpaBgEF0r_qLolVkRUFoGXCV26Dbk0YCF50dWb_6rh9jT6kSh48kKYkfh0Acb8Helm_q3tQwH9XHhLvCC6HXucXwUOnzr6DAuH3j7GRzciBxUfuPNu4s7NoqwV4G5gg4U0s4niso83_JM5JlUKCWgv4youmVqm3FCLoXNSu9cibb5AnUtV80XHtW6OSJbmb4moFIx5djS3iE6UEoZ8MPWsFitserZAcqj_kL_aRClJ-gM-dd4KHW85aoV_cyzYDJFzcAwRw26N4NacLjHkfi9-VJumBpkujweJj-LiwTxeMYeJ8j5DKfjgaTfZ-hMHCHdSPi-5EeScawfGW0keL3cuhr1-b_6MGOjvvuaP59lJ6bESOM4ZINhr0cYV5QLB4hKjrMAdgTkal9HspA37avW0mgUed0N1cr4VUpusDQHQZ0uP-Ltfcz4r65BOn330L4h7xixiNKwYQehidsO5fw_j_w8w32HAIwcMkVNyE0b3TelIIiKfBWFa6GvYu3n-1WnFKo8te0Ys8VODSe-_UbsmKuag0bZ94FnNpR6ptchgJuleaCVqomUN1pn2D-fseNwlhYv89djQ
base_path: .
base_url: https://api.crowdin.com
preserve_hierarchy: true
files:
  # JSON translation files
  - source: /src/lang/en.json
    translation: /src/lang/%locale%.json
  # Docs Markdown files
  - source: /src/**/en.mdx
    translation: /%original_path%/%locale%.mdx
